// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "theme_switcher"
import "copy"
import "paste_image"
import "image_modal"
import "log_card_click"
import "trix"
import "@rails/actiontext"
import "trix_custom"
